"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
type Run={id:string;status:string;task:string;repository:string;tests:string;cost_usd:number;created_at:string};
export default function Home(){
 const [token,setToken]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [tenant,setTenant]=useState("");
 const [repo,setRepo]=useState("demo://calculator"),[task,setTask]=useState("Add a subtract function to the calculator"),[runs,setRuns]=useState<Run[]>([]),[error,setError]=useState("");
 async function auth(path:string){setError("");const r=await fetch(`${API}/api/v1/auth/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(path==="register"?{email,password,tenant_name:tenant}:{email,password})});const d=await r.json();if(!r.ok){setError(d.detail||"Authentication failed");return}setToken(d.access_token)}
 async function refresh(){if(!token)return;const r=await fetch(`${API}/api/v1/runs`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok)setRuns(await r.json())}
 useEffect(()=>{refresh()},[token]);
 async function execute(){setError("");const r=await fetch(`${API}/api/v1/runs`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,"X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({repository:repo,task,max_iterations:5,max_seconds:120})});const d=await r.json();if(!r.ok){setError(d.detail||"Run failed");return}const id=d.id;for(let i=0;i<60;i++){await new Promise(x=>setTimeout(x,1500));const x=await fetch(`${API}/api/v1/runs/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(x.ok){const run=await x.json();if(["success","failed","stopped"].includes(run.status)){await refresh();break}}}}
 return <main><header><div className="brand">FORGE<span>AI</span></div><div className="pill">MULTI-TENANT AI ENGINEERING PLATFORM</div></header>
 <section className="hero"><p className="eyebrow">PRODUCTION ARCHITECTURE</p><h1>Autonomous code changes.<br/><span>Isolated per tenant.</span></h1><p className="lead">ForgeAI turns engineering tasks into verified changes using tenant isolation, queued workers, sandboxed execution, audit trails and evaluation-first agent loops.</p></section>
 {!token?<section className="panel auth"><label>EMAIL</label><input value={email} onChange={e=>setEmail(e.target.value)}/><label>PASSWORD</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/><label>ORGANIZATION FOR NEW ACCOUNT</label><input value={tenant} onChange={e=>setTenant(e.target.value)}/><div className="actions"><button onClick={()=>auth("login")}>SIGN IN</button><button onClick={()=>auth("register")}>CREATE TENANT</button></div></section>:<><section className="panel"><label>REPOSITORY</label><input value={repo} onChange={e=>setRepo(e.target.value)}/><label>TASK</label><textarea value={task} onChange={e=>setTask(e.target.value)}/><button onClick={execute}>QUEUE AGENT RUN</button></section><section className="results"><h2>YOUR TENANT RUNS</h2>{runs.map(r=><div className="run" key={r.id}><b>{r.status.toUpperCase()}</b><span>{r.task}</span><small>{r.tests} tests · ${r.cost_usd.toFixed(4)}</small></div>)}</section></>}{error&&<pre className="error">{error}</pre>}
 <footer>ForgeAI 2.0 · PostgreSQL RLS · Redis queue · isolated workers · OpenTelemetry</footer></main>}
